---
title: "Research Projects"
website:
  navbar:
format:
  html: 
    page-layout: full
---

:::: panel-tabset
## Stroke Severity

This project was conducted in collaboration with the Kinesiology Department at UGA. My team and I analyzed electronic health records from stroke patients within the largest hospital system in Athens, GA, with the overall goal of helping establish a patient recruitment network to advance UGA-based stroke research. We investigated how demographic factors and comorbidities influence length of stay and discharge destination. In summary, we found that admission stroke severity scores and admission unit were key predictors. I have included the final poster and presentation slides below.

::: panel-tabset

## Poster
```{=html}
<iframe width="100%" height="700" src="files/stroke-poster.pdf"></iframe>
```

## Presentation
```{=html}
<iframe width="100%" height="700" src="files/stroke-presentation.pdf"></iframe>
```
:::

## NPS in Alzheimer's

This project was conducted at UC Irvine with the ISI-BUDS program. My team and I investigated neuropsychiatric symptoms (NPS) in patients with Alzheimer's disease (AD) associated with Down syndrome (DS). While NPS have been well studied in late-onset AD, their effects in patients with AD due to DS remain a gap in the literature. We found that NPS in DS and older adults were similar across cognitive groups, including cognitively stable, mild cognitive impairment, and clinical dementia. These similarities in the two groups may reflect shared amyloid or related pathology. Read more about our research here!

::: panel-tabset

## Poster
```{=html}
<iframe width="100%" height="700" src="files/alz-poster.pdf"></iframe>
```

## Presentation
```{=html}
<iframe width="100%" height="700" src="files/alz-presentation.pdf"></iframe>
```

## Paper
```{=html}
<iframe width="100%" height="700" src="files/alz-pub.pdf"></iframe>
```
:::

## Lung Cancer Costs

This project was conducted at Columbia University with the BEST program. I analyzed cost trajectories for lung cancer patients and compared outcomes between non-Hispanic Black and non-Hispanic White patients. I found that non-Hispanic Black patients had a lower survival probability than non-Hispanic White patients, and a significant cost differences persisted across Medicare Parts A and B and Part D. The research poster below displays some additional analysis done.

```{=html}
<iframe width="100%" height="700" src="files/lc-costs-poster.pdf"></iframe>
```
:::