project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: uga.qmd
        text: UGA
      - href: cv/cv-lidio-jaimes.pdf
        text: CV

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual